
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUKHLIS
 */
public class AgeForm extends javax.swing.JFrame {

    /**
     * Creates new form AgeForm
     */
    int pX;
    int pY;
    public AgeForm() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jexit = new javax.swing.JLabel();
        jminimize = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jyear = new javax.swing.JTextField();
        jmonth = new javax.swing.JTextField();
        jday = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Years = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Months = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Days = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Hours = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Minutes = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Seconds = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Age Calculator");

        jexit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jexit.setForeground(new java.awt.Color(204, 204, 204));
        jexit.setText("x");
        jexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jexitMouseClicked(evt);
            }
        });

        jminimize.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jminimize.setForeground(new java.awt.Color(204, 204, 204));
        jminimize.setText("-");
        jminimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jminimizeMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linecons_e02b(0)_32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jminimize)
                .addGap(18, 18, 18)
                .addComponent(jexit)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jexit)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jminimize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Enter Your Date OF Birth:");

        jLabel4.setText("Year");

        jLabel5.setText("Month");

        jLabel6.setText("Day");

        jyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jyear.setMaximumSize(new java.awt.Dimension(4, 4));
        jyear.setMinimumSize(new java.awt.Dimension(4, 4));
        jyear.setPreferredSize(new java.awt.Dimension(4, 4));
        jyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jyearFocusLost(evt);
            }
        });
        jyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jyearActionPerformed(evt);
            }
        });
        jyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jyearKeyTyped(evt);
            }
        });

        jmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmonth.setMaximumSize(new java.awt.Dimension(4, 4));
        jmonth.setMinimumSize(new java.awt.Dimension(4, 4));
        jmonth.setPreferredSize(new java.awt.Dimension(4, 4));
        jmonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jmonthFocusLost(evt);
            }
        });
        jmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmonthActionPerformed(evt);
            }
        });
        jmonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jmonthKeyTyped(evt);
            }
        });

        jday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jday.setMaximumSize(new java.awt.Dimension(4, 4));
        jday.setMinimumSize(new java.awt.Dimension(4, 4));
        jday.setPreferredSize(new java.awt.Dimension(4, 4));
        jday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdayFocusLost(evt);
            }
        });
        jday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdayActionPerformed(evt);
            }
        });
        jday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdayKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Your Complete Current Age Is:");

        jLabel8.setText("Year");

        Years.setEditable(false);
        Years.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Years.setMaximumSize(new java.awt.Dimension(4, 4));
        Years.setMinimumSize(new java.awt.Dimension(4, 4));
        Years.setPreferredSize(new java.awt.Dimension(4, 4));
        Years.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearsActionPerformed(evt);
            }
        });

        jLabel9.setText("Month");

        Months.setEditable(false);
        Months.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Months.setMaximumSize(new java.awt.Dimension(4, 4));
        Months.setMinimumSize(new java.awt.Dimension(4, 4));
        Months.setPreferredSize(new java.awt.Dimension(4, 4));
        Months.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthsActionPerformed(evt);
            }
        });

        jLabel10.setText("Day");

        Days.setEditable(false);
        Days.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Days.setMaximumSize(new java.awt.Dimension(4, 4));
        Days.setMinimumSize(new java.awt.Dimension(4, 4));
        Days.setPreferredSize(new java.awt.Dimension(4, 4));
        Days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaysActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Your Age In Hour Is:");

        Hours.setEditable(false);
        Hours.setMaximumSize(new java.awt.Dimension(4, 4));
        Hours.setMinimumSize(new java.awt.Dimension(4, 4));
        Hours.setPreferredSize(new java.awt.Dimension(4, 4));
        Hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoursActionPerformed(evt);
            }
        });

        jLabel12.setText("Hours");

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Your Age In Minute Is:");

        jLabel14.setText("Minutes");

        Minutes.setEditable(false);
        Minutes.setMaximumSize(new java.awt.Dimension(4, 4));
        Minutes.setMinimumSize(new java.awt.Dimension(4, 4));
        Minutes.setPreferredSize(new java.awt.Dimension(4, 4));
        Minutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinutesActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Your Age In Second Is:");

        jLabel16.setText("Seconds");

        Seconds.setEditable(false);
        Seconds.setMaximumSize(new java.awt.Dimension(4, 4));
        Seconds.setMinimumSize(new java.awt.Dimension(4, 4));
        Seconds.setPreferredSize(new java.awt.Dimension(4, 4));
        Seconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondsActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Get Age");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jyear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jday, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Years, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Months, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Days, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6))
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(23, 23, 23)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Minutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jyear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jday, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Years, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Months, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Days, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jexitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_jexitMouseClicked

    private void jminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jminimizeMouseClicked

    private void jyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jyearActionPerformed
        /*if(jyear.getText().length()==4){
            jyear.setText(jyear.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Please Input Valid Year", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
        */
       
        
        
    }//GEN-LAST:event_jyearActionPerformed

    private void jmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmonthActionPerformed

    private void jdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdayActionPerformed

    private void YearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearsActionPerformed
        
        
        
    }//GEN-LAST:event_YearsActionPerformed
     
    private void MonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthsActionPerformed

    private void DaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DaysActionPerformed

    private void HoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoursActionPerformed

    private void MinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinutesActionPerformed

    private void SecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      /*  if(jyear.getText().equals("") || jmonth.getText().equals("") || jday.getText().equals("")){
            jButton1.setEnabled(false);
        }
        else{
            jButton1.setEnabled(true);}*/
        
    
            int yy =Integer.parseInt(jyear.getText());
        int mm=Integer.parseInt(jmonth.getText());
        int dd=Integer.parseInt(jday.getText());
        LocalDate today = LocalDate.now();
        if(yy>today.getYear()){
            JOptionPane.showMessageDialog(this, "Invalid Year Input", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
        else 
            if(mm<0 || mm>12){
                JOptionPane.showMessageDialog(this, "Invalid Month Input", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                jmonth.setText("");
        }
        else
                if(dd<0 || dd>31){
                    JOptionPane.showMessageDialog(this, "Invalid Day Input", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    jmonth.setText("");
                }
                else{
                    int calyear=Integer.parseInt(jyear.getText());
                    int calmonth=Integer.parseInt(jmonth.getText());
                    int calday=Integer.parseInt(jday.getText());
                    LocalDate birthday= LocalDate.of(calyear, calmonth,calday);

        
                   Period p = Period.between(birthday, today);
                   Years.setText(Integer.toString(p.getYears()));
                   Months.setText(Integer.toString(p.getMonths()));
                   Days.setText(Integer.toString(p.getDays()));
                }
        
                   int calyear=Integer.parseInt(jyear.getText());
                   int calmonth=Integer.parseInt(jmonth.getText());
                   int calday=Integer.parseInt(jday.getText());
                   LocalDate birthday= LocalDate.of(calyear, calmonth,calday);

        
                   Period p = Period.between(birthday, today);
                   Years.setText(Integer.toString(p.getYears()));
                   Months.setText(Integer.toString(p.getMonths()));
                   Days.setText(Integer.toString(p.getDays()));
                   
                   Hours.setText(Integer.toString(p.getYears()*365*24)+(p.getMonths()*30*24)+(p.getDays()*24));
                   Minutes.setText(Integer.toString(p.getYears()*365*24*60)+(p.getMonths()*30*24*60)+(p.getDays()*24*60));
                   Seconds.setText(Integer.toString(p.getYears()*365*24*60*60)+(p.getMonths()*30*24*60*60)+(p.getDays()*24*60*60));
   
            
        //}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jyearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jyearKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_BACK_SPACE))){
            
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jyearKeyTyped

    private void jmonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmonthKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_BACK_SPACE))){
            
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jmonthKeyTyped

    private void jdayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdayKeyTyped
         char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_BACK_SPACE))){
            
            getToolkit().beep();
            evt.consume();
        }
      
    }//GEN-LAST:event_jdayKeyTyped

    private void jyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jyearFocusLost
        if(jyear.getText().length()==4){
            jyear.setText(jyear.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter Correct Year", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            jyear.setText("");
        }
    }//GEN-LAST:event_jyearFocusLost

    private void jmonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jmonthFocusLost
         if(jmonth.getText().length()==1 || jmonth.getText().length()==2){
            jmonth.setText(jmonth.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter Correct Month", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            jmonth.setText("");
        }
    }//GEN-LAST:event_jmonthFocusLost

    private void jdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdayFocusLost
        if(jday.getText().length()==1 || jday.getText().length()==2){
            jday.setText(jday.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter Correct Day", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            jday.setText("");
        }
    }//GEN-LAST:event_jdayFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        pX=evt.getX();
        pY=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        setLocation(getLocation().x+evt.getX()-pX, getLocation().y+evt.getY()-pY);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Days;
    private javax.swing.JTextField Hours;
    private javax.swing.JTextField Minutes;
    private javax.swing.JTextField Months;
    private javax.swing.JTextField Seconds;
    private javax.swing.JTextField Years;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jday;
    private javax.swing.JLabel jexit;
    private javax.swing.JLabel jminimize;
    private javax.swing.JTextField jmonth;
    private javax.swing.JTextField jyear;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("image.png")));
    }
}
class Calculate {
    
    public static int day;
    public static int month;
    public static int year;
    
    
   
    public static void setDay(int dd){
        day=dd;
    }
    public static void setMonth(int mm){
        month=mm;
    }
    public static void setYear(int yy){
        year=yy;
    }
    
    public static int getYear(){
        return year;
    }
    public static int getDay(){
        return day;
    }
    public static int getMonth(){
        return month;
    }
}
